services:
    db:
        build:
            context: .
            dockerfile: Dockerfile.db
        command: --max_connections=200000
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_USER: db
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
    redis:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
volumes:
    db_data: