services:
    php:
        build:
            context: .
            target: php
        volumes:
            - ./:/var/www/html
        networks:
            - laravel
        depends_on:
            - db
            - redis

    nginx:
        build:
            context: .
            target: nginx
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www/html
        networks:
            - laravel
        depends_on:
            - php

    db:
        build:
            context: .
            dockerfile: Dockerfile.db
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_USER: db
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel
        ports:
            - "3306:3306"
    redis:
        image: redis:latest
        restart: always
        networks:
            - laravel
        ports:
            - "6379:6379"
volumes:
    db_data:
networks:
    laravel:
        driver: bridge
